name: CI actions
on:
  pull_request:
    branches:
      - main

jobs:
  run-eslint:
    runs-on: ubuntu-latest

    steps:
      - name: actions-checkout
        uses: actions/checkout@v3
      - name: eslint-check
        run: |
          yarn install  
          yarn lint

  build:
    runs-on: ubuntu-latest
    needs: [run-eslint]

    steps:
      - name: actions-checkout
        uses: actions/checkout@v3
      - name: Project build
        run: |
          yarn install
          yarn build

  run-tests:
    runs-on: ubuntu-latest
    needs: [run-eslint]

    steps:
      - name: actions-checkout
        uses: actions/checkout@v3
      - name: Tests running
        run: |
          yarn install
          yarn test
